### ISSUE TITLE
Crash on sentry package (for test users?)

### ISSUE THREAD

**Issue by jreenen** [jreenen/com.jreenen.homeyharmonyhub#75]
/node_modules/@sentry/node/dist/parsers.js:28
var mainModule = ((require.main && require.main.filename && utils_1.dirname(require.main.filename)) ||
                                                                    ^

TypeError: utils_1.dirname is not a function
    at Object.<anonymous> (/node_modules/@sentry/node/dist/parsers.js:28:69)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at Module.require (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/index.js:1:191)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/node_modules/@sentry/node/dist/backend.js:6:17)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)

**Comment by jreenen** [comment]
Will remove the Sentry implementation inside the app.
