### ISSUE TITLE
Crash report on device driver: Cannot read property 'friendlyName' of undefined 

### ISSUE THREAD

**Issue by jreenen** [jreenen/com.jreenen.homeyharmonyhub#76]
Synchub error: TypeError: Cannot read property 'friendlyName' of undefined
TypeError: Cannot read property 'friendlyName' of undefined
    at HarmonyDevice.triggerOnOffAction (/drivers/harmony_device_driver/device.js:192:24)
    at HubDevice.<anonymous> (/drivers/harmony_device_driver/device.js:144:26)
    at HubDevice.emit (events.js:323:22)
    at HubDevice.EventEmitter.emit (domain.js:482:12)
    at HubDevice.handleDeviceStateChanged (/lib/hubdevice.js:22:14)
    at Hub.emit (events.js:311:20)
    at Hub.EventEmitter.emit (domain.js:482:12)
    at HubActivity.handleActivityChanged (/lib/hubactivity.js:36:29)
    at Hub.emit (events.js:311:20)
    at Hub.EventEmitter.emit (domain.js:482:12)

**Comment by jreenen** [comment]
Working on a fix
